### ISSUE TITLE
xRequires test in Test000-Module.Tests needs updating

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#98]
xRequires test in Test000-Module.Tests needs updating now that it is no longer a Global function:

[-] Checking xRequires Private Function exists 36ms
   Expected: {System.Management.Automation.RuntimeException: vRA Connection variable does not exist. Please run Connect-vRAServer first to create it}
   But was:  {System.Management.Automation.CommandNotFoundException: The term 'xRequires' is not recognized as the name of a cmdlet, function, script file, or o
perable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
      at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)}
   at line: 19 in /Users/jon_medd/Development/PowerShell/Tests/7.1/Test000-Module.Tests.ps1
   19:         $Error[0].Exception | Should be "System.Management.Automation.RuntimeException: vRA Connection variable does not exist. Please run Connect-vRASer
ver first to create it"

**Comment by jonathanmedd** [comment]
Fixed with the above commit
